### PR TITLE
Fix nautilus 4.0

### PR DESCRIPTION
**Pull request by graphicore**
Hi, the plugins failed for me with a ValueError:

```
nautilus_python_load_file: entered filename=nec-exif
Traceback (most recent call last):
  File "/home/commander/.local/share/nautilus-python/extensions/nec-exif.py", line 6, in <module>
    gi.require_version('Nautilus', '3.0')
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 4.0
```

The [first commit](a0d155b46f067bf43234cd5ce7ccd9270b429317) fixes that for `gi.require_version('Nautilus', '3.0')`.

Then I got occasionally an error that is however hard to reproduce:

```
Traceback (most recent call last):
  File "/home/commander/.local/share/nautilus-python/extensions/nec-exif.py", line 90, in do_event
    filename = file_info.get_location().get_path()
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NautilusVFSFile' object has no attribute 'get_location'
```

I fixed this in the [second commit](b007990ce6f0049ff0c27ec4144f4d5375aa5874) by using the same method used in the nautilus-python examples https://gitlab.gnome.org/GNOME/nautilus-python/-/blob/0eaaad1a44c4fd1d7324dfb97fd8c382d59cd4e3/examples/block-size-column.py#L24

But I'm not sure if that is backward compatible to Nautilus version 3.0, so there's a conditional assignment depending on `gi.get_required_version('Nautilus') == '3.0'` and the `unquote` dependency is also only imported for Nautilus version 4.0.

### CODE REVIEW

**Comment by chumariesco** [comment]
Hi!
Can the extension anyhow work with nautilus 4.0?
I added the commits made by @graphicore and installed it, but no new columns options appear in Nautilus. This would be so super helpful for me, since [nautilus-columns](https://github.com/atareao/nautilus-columns) is also broken for Nautilus 4.0.
columns_nautilus
